### ISSUE TITLE
Markiplier E

### ISSUE THREAD

**Issue by yeskunall** [eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#243]
I just wanted to say...

![](https://i.kym-cdn.com/entries/icons/original/000/026/008/Screen_Shot_2018-04-25_at_12.24.22_PM.png)

Thank you for your attention.

**Comment by nightpool** [comment]
this is less funny when you don't see the filename like I can in my email
