### ISSUE TITLE
what sense with this repo?

### ISSUE THREAD

**Issue by FoxDaxian** [eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#273]
I don't understad.

**Comment by orlys** [comment]
Eee,
e eeeeeee ee
[Eee eeeeeee e eeeeeee eeeeeeeeee](https://github.com/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/issues/269)

**Comment by FoxDaxian** [comment]
alright, I'm out, i still understand.
I did't see about it content ever, and I'm in china.  :D

**Comment by ZaneHannanAU** [comment]
the tldr is that it's repetitive printing of a character in various languages.

**Comment by FoxDaxian** [comment]
> the tldr is that it's repetitive printing of a character in various languages.

wow, this repo get so moch attention , just because of above quote. :D

**Comment by iliana** [comment]
it appears the issue resolved itself

thanks everyone
