### ISSUE TITLE
How about giving a readable document about this project

### ISSUE THREAD

**Issue by lylex** [eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#301]
I just get so confused after read this project. Even can not sleep...

**Comment by markrousell** [comment]
You can infer the purpose of the project from the source files within.

It's very silly, but funny.

**Comment by iliana** [comment]
closed wontfix

**Comment by quat1024** [comment]
I don't have any trouble reading the README.md file. It seems to perfectly describe the contents of the repo
