### ISSUE TITLE
WTF. don't make github stupid as you :<

### ISSUE THREAD

**Issue by xiaobogaga** [eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#346]
Hey, guys? why you make this repository, I know it's funny, but this is not github style, OK? 

please tell me what this repository can do except that it shows how stupid you are. I would close this
if you confirm me.

If it is used for testing or learning, OK, fine. but can you make this private.

**Comment by Ivlyth** [comment]
i would suggest you to change `W*** T** F***` to `WTF`

**Comment by sgkoishi** [comment]
![](https://img.shields.io/github/stars/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.svg) ![](https://img.shields.io/github/forks/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.svg)
I guess people love it.
[You can star repositories to keep track of projects you find interesting and discover similar projects in your news feed.](https://help.github.com/articles/about-stars/)

**Comment by kiding** [comment]
someone doesnt get enough e

**Comment by iczero** [comment]
have more e
![](https://i.kym-cdn.com/entries/icons/original/000/026/008/Screen_Shot_2018-04-25_at_12.24.22_PM.png)
