### ISSUE TITLE
e - 2.718281828..

### ISSUE THREAD

**Issue by ralphtheninja** [eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#375]

**Comment by iczero** [comment]
e.
![](https://i.kym-cdn.com/entries/icons/original/000/026/008/Screen_Shot_2018-04-25_at_12.24.22_PM.png)

**Comment by ralphtheninja** [comment]
![e](https://user-images.githubusercontent.com/308049/49711415-7328e800-fc3f-11e8-89c8-6dabf64b48bd.gif)

**Comment by iliana** [comment]
#27

**Comment by ralphtheninja** [comment]
@ilianaw Thanks! Will re-open if `e` changes.
