### ISSUE TITLE
please add a license

### ISSUE THREAD

**Issue by iczero** [eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#381]
it needs to be open source!!!!
edit: it appears the WTFPL was mentioned previously

**Comment by iliana** [comment]
at this point it would be impossible to get every contributor to agree on a single license so we're not going to bother

**Comment by iczero** [comment]
Oh. Forgot about that part
