### ISSUE TITLE
世界上最好的语言是PHP，没有之一，不服来辩！！！

### ISSUE THREAD

**Issue by xumengsi** [eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#418]
The world's best language is PHP, no one, not convinced to argue!!!

**Comment by HsiangHo** [comment]
![image](https://user-images.githubusercontent.com/29297882/49723696-70131380-fca2-11e8-8d44-a5435152c5a1.png)
