### ISSUE TITLE
U̾͑̍̽̓̋͛ͣͪ͛̿̾ͮ̾͂̚͏҉̦̰̻̘͇̭͕̖̣ͅ5̸̢̯̗̺̤̓̂̐ͯ͂̂̇̌̈ͩ̈̓͆ͯ̉̎̓̂ͅ ̓̄̽ͫͦ̆ͫͩ͗ͤͨ́͏̨̫̲̬͙̤̯͍̺̹̹Ḩ̴̼͎̟̪̳̗̣̩̻̙̻̜̻͉̥͗̾̑̂̿̈́ͧ̚̕͡È̸̡̠̳̮͇ͯͮ͑̽̒̔̂͆ͨ̾̾̚̚Ļ̶̸̷͙͕͍̪̰̹͎̖͙̠͇̱̪͙͇͆͋̇̐͗͆͞p̭̪͓̻͕̙̲͓̯͖̭͍̓̃ͧ̓̏̊̈́ͯͧͩͨ͗̈́̕ͅ ̵̵͙̲̮̥̟̭͗ͭ͑̽̍ͥ̃͛͂

### ISSUE THREAD

**Issue by Qdafengzi** [eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#428]
̶̝͈͇̮̫̝͍̱̣̼̳̲̱̯ͥ̌̔ͥ̒͊̀ͭ͡ͅU̾͑̍̽̓̋͛ͣͪ͛̿̾ͮ̾͂̚͏҉̦̰̻̘͇̭͕̖̣ͅ5̸̢̯̗̺̤̓̂̐ͯ͂̂̇̌̈ͩ̈̓͆ͯ̉̎̓̂ͅ ̓̄̽ͫͦ̆ͫͩ͗ͤͨ́͏̨̫̲̬͙̤̯͍̺̹̹Ḩ̴̼͎̟̪̳̗̣̩̻̙̻̜̻͉̥͗̾̑̂̿̈́ͧ̚̕͡È̸̡̠̳̮͇ͯͮ͑̽̒̔̂͆ͨ̾̾̚̚Ļ̶̸̷͙͕͍̪̰̹͎̖͙̠͇̱̪͙͇͆͋̇̐͗͆͞p̭̪͓̻͕̙̲͓̯͖̭͍̓̃ͧ̓̏̊̈́ͯͧͩͨ͗̈́̕ͅ ̵̵͙̲̮̥̟̭͗ͭ͑̽̍ͥ̃͛͂F̨̯̭̰͖̜͇͎͈̤̥̥̬͋́̆̃̆ͪ̄͗ͩͨ̎́ͪ̆̌̿̑́1̷̲̼̠̻̫̮̹̜̜̠̣̤̎ͬͪ̔̆̎̓ͨ̈̋ͪ͗̏ͦͥ͞N̗̮͓͉̪̫̯͕̻̦̥̍ͧ̑̾̌ͪ͒͋̈ͨ̓̇ͧ̊͂́̚͘͠D̡̢̰̫̫̱̑͒̓ͫ͋ͪͤ̃̔̊ͪ̽̽ ͪ̈ͫ͗̌ͣ̉̽ͤ́ͨ͠͏̷̵̞͇̬̦̱͡ͅ|̶̨̛͇̫̰̦̳̣͈̝̇͛̿ͭ̃ͧͪͥ͋̆ͪͅͅ-̡̛̮͓͇̤̪͈̎ͥͥ̄̎̄̃͛̀͡͠|̷̻̬̦̰̪͇͎͈͔̟̙͖̯̣̀̾̾̑͊̊̐̍̌ͪ̓̾͋̐̔̑̆̊̕@ͦͪ͗͂̏̐́ͣ̋ͣ̀̄͑͌̆ͥ̂́͏̡͍̼͖̼̲̰̱̰̪̝̤͎͎̩͇̠͘v̨̢̥͈͛͆ͩ̏̒ͫ͋͌ͦ̂̒͑̓ͭ̕ͅͅ3̈͂̀̈́͏̡̙̭͖̦̠͇̱̞̙̗͓͇̜͉͔͎̤͢͢͟ͅ ̵̢̟̖̬̩͕̤̳̩̯͓͈͈͓̲͈ͫ̎̂̋̏͂ͫ́̔ͨͧ̒̚̕͟͡ͅj̵̡̢͍͎͈̣̟͖̻̞̈̋̑̎̇͋̇̐̄̔̆̋͟͝ͅo̢͆̂̾͗ͫ͌̈́̈́͒͑̚͠҉̨̼͍̩͈̯͇̬̻͉̼̟̗̥͍͔̘͎o̡̼̼͍͖̺̺͍̩̘̮̱̳̽̽̒̂̅ͦ̅̈̐́̆ͬ͌́̚̕,̶̸̜̻̯̹̗̗̳̪̝̜̣̞̖̝͇̭͓̎ͫ̄ͥ̐̇̎̑̔ͮ̏̂̓͡͞ ̛͓̝͇͍͇̰͎̖͉̘̗͔͖͇̝̞̰̻̇̂̆̇̍́͠ȗ̶̧͓͓̗̮̠̩̘̠̟ͦͬ̓̌ͣ̊ͬ͆ͭ̄ͫͥ͟͠5̢͕͇̳̳̞̰̻̤̘̺̠͖̱͎̙̾͗̽ͤ̔ͥ̄͆̏͐͋ͣ̏ͧ̉̿̇͒͡ͅ ̸͊ͣͧ̈́ͥ̆̈́̀͜͝͏̵͇̰̳͙͉̲͉͈͉̟̼̜̖̝̜̣9ͦ͆ͫ͛̄͊̒̎̒ͫͣ̄̔ͬ̅͏̱̹͇͇̳̯̺͈̭͍̣͈̻̘̕3̧̄̋ͣ҉̵̗̝̜͇̹̣͓͉̟̖̼̹̘̪͎͎̗̺̕͠t̨̛̮͇͇̲̞͉̻̱̻̥͕̦̭̹̻͙̅ͭ̏ͣͬ́͢ͅ ̷̡̨̮͕͍̺̮̜̟̗̼͇̲̪͓̥̘͙̼̙̓̐̒̀͋ͬͧ̇ͧ́͝k̸̠͕͕͕̭̪̭̺͖̮̬̳̤̪̱̳̳ͯͪ̑̆̋̄̽̽ͭ̍͑ͪ̈̚n̵͎͉̳̲͈̬̟̅ͨ̃̑͞0̸̼͖̬͔̗͓̺͙̼̟̩̤̦̺͗ͯ͛̓ͬ̿̈́̌̊͂͛͝ͅẁ̨̛̜̘̯͍͎̻̦̓ͧ͋̎̒͢͟ ̸̧̢̧̮͓̹͎̟̦̲̙͖͕̦̫̳̬̟̲͎̜̹͑͆̂̇͑̉̓̏ͪ̽͐ͬ̎̀̚4̶̴̢͕̞̺̲̙̮͖̥͈̠̜̤̺͂̈́ͦ̈́̅̀ͥ͝|̶̶̧̙̳͕̺̜͇̮̰̖̦̜̻͕̤̻̫̞͙̔ͬ̓̽͗͊̌͆ͨͬͯ\̡̫̤͚̉͋̌̀͢ͅ|̐ͦ̇ͤ̆̌̊͌̏̉͒̅͋̑͏̧̻̣̟̘͙̬͍͙̥̳̫̘̫̪d̶̴̗̝̜̬͎̮̦̜͓͔̰͔̻͇̠̖̬̗̤ͩ͒̾̇̀́ ̶̪̹͎͍͖̟̣͖̪̹͉̣̪̳̣ͩͫ͆̈́̈́̐́̐̂͋ͭ͑ͦ̍ͯ͂ͩͩ̀͜5̶̃ͭͬ͋̆̈́̑̏ͫ̓͟͠͝҉̭̖͓̭̮̱̞͔̻͎̤̮̗̯̠͎͍I̡̽ͤ̍̈́̊ͥ̐̒͆̾͒̅ͫ̒ͥ̽͂͏̶̡̳̗̲̣ṯ̢̛̖̘̣̣͚͈̬͓̼̺̰̆́̔ͣ̑ͧ̓̿̆ͯ̌̀̎ͭ̓ͥ̀̀̚ͅ3̨̧͍̫̭̳̦̝̪̝̹̹̹̥͓͙̜̀͛ͭ̈́ͭ̃̈́͆̍̍̆̅̓ͪͫ̊̍͆͘͜͡5̨̧̢̝̣̜͍̜̪̭̬̞̩̊͊͐͑̓̔̒ͦ̃͗ͩ́͋ͨ̀ͯ̀͝.̡̡̪̮̯̼̭̜̣̯ͤ̋ͮ̆̔̂ͥͬ͆̽ͧͤ̈́̄ ̴̧̧̫̩̪͉͖̣̦͔̞̈ͣͥ͊̽ͯ̍̇ͪͣ̉͌̀̌̚̕͟D̢̢̟͖͙̲͎̩͈̝̙̟͍̺̹̗͉̳͙͔̽̉̾͊ͥ̔ͨ̐ͧ̾̑́̀͢4̢͓̲͎͓̦̺̩̣̬͎̖̣͕̪̞̃ͩ̊ͯ̒̂̂̈́͋̌̔͠͠͠ͅ ͎̺͖͙̲̼͉̱͙̪̭̺̦̣̦͔͕ͪͭͪ̓ͯ̍̀͜͠͝(̵̢̀̈́̈̆̒̌́̀͏̯̜̤̗̥̗̲1̸̬̻̮̜̫̦͍̜̥̩̂̅̒͌ͬͣ́͜f̓̔̃̒ͪ̾͆̐̿̄̋ͣ̍̄̃̽̚͏̛͎̗̬͉̠̯̖͚̪͓̪͢ ̶̡̨̢̻̲̻͓̦͓̳͈̻̦̬̭̰͉ͤ̋ͭ͑͆̌̾̅̚͡b̝͕͍̘̠̭̯ͧͣͣͧ͊̕͝|̸̶̛͉̜̥̭̤̲͖͚͙̭̩̓ͣͭ͛͌̎̾̕͟0̨̜̙͉̹̮̥̞̙̳̫̱̜ͯ͊̓ͯͬ̑ͪ̄ͧ̎̀͢0̴̧̳̬͇̪̗̩̣̗̗͙̤͇͕̣͉̏̑͗ͬͤ͌ͤ̏̓̒̐̍̍ͩ͗͜͝ ̵̨̳̭̭͇̙̘̘͚͇̰͚̹̫̉̓̉̎ͯͬͬ͆͐̍ͤͤ͊ͬ́́͜+̴̷̢̫͙͇̥̘̰͔̞̬̱̮̬͓̼̑͒ͯ͊̓ͫ͊͊̽̓̕H̛̎̉̿̌̃̊̈͊̂ͩ̾ͭ̚͏̩͉̰̰̱̤̯͔̺̪͖̜̱@̸̱͖͍͍͚͍̫̺̭͎̮̼̘̱̪̃͂ͨͮͤͥ͌̎ͮ̅̿ͮ̋͆͢T̴̡̞̱̱̠̗͎̯ͩ̿͂̇̉ͩ̀̅̐ͮͣ̅́̚͝ ̡̧̧̲͍̝̲͕͍̼͓̞͇̭͍͙̜̬̳̥͙͐ͬ̈͊ͬͥ͊̅̐͒͘͠5̵̛̺̦̭̣͙̳̘̦͎ͥ̈́͌̔(̠̯̩͈̜͉̭̣͕̯̺̪͈̼͈̻̘̓ͣ̈́̓ͩ͗̂̊͌ͣͭͪ̚͟͢͢͝0̸ͪ̐͛͋̈́̽̅͌̓͑͛ͭ̿̾͏̡̗̙̹̮̯̗͇̫̮̥͈ù̷̶̃ͬ͆̎ͦ̓̋̆̐͆̿͏̷̱͍̤͚̖̦̤͍͍̬͔̺̕7̡̣͖̪̖͍̼̩͎̥̹̙̲͙̞̓͗̂͌ͥ̒̆̃͂̀ş̴̸͍̲̼͈̯͆ͭͣͣ̾ͪ́͠ͅ,̧̙̙̻̖̼̺̼̺́͊ͣ̓̋̎͊̃͌͐̐ͣ́̈́ͣ͋́͘̕͟ͅ ̷̧̱̪̹͎̼̮̻̙̰̗̖̗̯̩̞̃ͩ̀̈́̓͋ͪ̿ͥ͂͋ͤ̇͜ͅͅͅr̡̠̘̦͍̹̥̆͑̇ͣͣ1̵̶͎̰͈̫͕̱̞̩͑ͥ̄̏͆̽̉ͫ͑̆̑͋͠͞ṫ̴̛͈̯̻͖̝̙͈̖ͨͧ̿ͨͪͬ̑ͨ̈̽ͥę̶̵̱̪̤͉̗͐̎̉ͬͧͥͯͩͥ̋͆z̷̦̳͕̖̭̦̬̲̟̅̇ͯ͝ ̨̜̟̖͈͇̗̞͖̬̯̮͔͙͔͗̇̽̇̎͆̅͂̽̊̈́͢͟͡R̸̠͔͎͛͊ͨ͑ͤͯ̿̈͂̃ͧ͂ͦͪͦ̎̚͝e̸̤͖̰̼̙͙̫͉̦̦̯͇̰̠̱͆̆̾̅̆͗̓̄̈͗̈ͭ̅́́̍͋ͮ̈́͜ͅ@̨̛̊̅͊͗̆ͧ͆̄̿̓ͤͥ̋͏̠̜͇͎͚͉̰̗͙̠̲̜͎͝ͅr͎͔̯̜̖̪̩̖̫̯̱̜̲̆ͨ̇̈́͗̎́͡c͋̈͐́ͤ̂ͦ̈ͧͯͣͫ́ͣͥ̐̐͊͘͠͏͚̪̖̥̫̕H͗̉̓ͥ̅̂͗̆͛҉̛͟҉̟̬͉̻͉͚̫͝1ͤ̓̈͌̽̈́ͮ͒͑̚͏̢͖̩͙͍̺́͘ͅN̶̖͍̣̺͙ͬ̆͐ͣ̍ͣͮͧ̌̀ͩ́̉̈ͨͩ͗̍́͢͢͞ģ̾͆ͧ͂̔ͭ͂̽̑ͧ͗ͤ͊ͪ̂͘͏͔͈͙͔̬̞͎̯͎̱̠͓͢͝ ̨̻͚̟̼͎̼̮̪̖͔̘̭̺̞͔̮̅͌̄̃͂͆̏͆ͩ͋̂̑t̎ͯ̏̒͌̇̍̓̃̽͌ͭ̾̇͛̈͘҉̴̵̦̹̙̠͉̭̟̘͇̫̱̩͢ͅ3̙͕̣̳̓̅ͭͦ̎̑̈́͒̏͊͋͒̾͢x̷̧̨̞̪̗̹̖̩͚͎͍̻͙̯͙̭͇͇̀ͤͯͮ͗̆̑̊̃͂̎ͨN̛̜͖̺͈̭͙͇̱̩̞ͤͪ͊̾ͪͬ̓̔ͫ̋ͯ͗́͠͞ͅ0̴̟͚̝̻̮̙̣̤̥͎̱ͫ͋̄ͥ̋̅̈́͐̉͆͗ͦ̀̐́̚͟͠ͅl̷̷̠̮͇̘̠͍̮̪̲̘̙̰̭ͫͤͭͥͣͮ́̂̅̐̕͞0̧̻̘̹̲̰̗̲͈̘̩̲̗̪̭̰͖̈ͭ͆ͣ̚͜ͅ9͆̿̽̀̔͋̊͐͗͂̈́҉͍͎̗͔̮̻͚̗̠̤̳̘̮̘̫̮̜̕3̛͖͙͔̖͓̱̠̘̓̉̽̔̒̿̀̚ͅ3ͦ̔ͩ͊̽͌̓ͤ̕҉̞̭̥̬̲̟̜̮̬̥͚̕,̞̲̬̼̰͓̜̗̤̳͇̬̯̩̔̓͆̏̽̏ͮͩͧ̔̄͌̈̏̀̽ͣ̀̀̕͟͞ͅͅ ̶ͪ͆ͯ͆҉̬͇͍͚̣̥̜͈͜͢͝y̝̞͉̝̼̮͇̲͔̟̍́̌̔̀̕̕0̢͕͎̣̠̣̭̫͇̜̰̿ͭ̓ͩ͘ ̖͔̹̪̗̖̘͍͖̣̜͔͉̗͔̯͍̭̀̃͋͑̽͛ͣͧͧ̀ͮ͑ͯ͐̎̌̂͑͘͘͜͟͞ň̶̡̬̣͖̟̿ͯ͐̈́̀̂ͫ̈̋0̨̛̪̮͎̙͕̞͕̱̮̜͙͍̣̖̘͚̠̲̍̎̽̋̋͐̏̾͊ͭ̐͝͝n̸̡̦͍͚̹̺͔̰̪̪͇̟̘̼̫ͫͧ́ͯ͗ͤ͋̈́̇ͯͬ̊̊̇.̴̵̸̠͙̣̬̗͕̱̇̌͛͑̽̓ͨ̆̀̽̑ͪ͘͠ͅ ̖̮̩͉̪̩̐̇ͭͨ̀́́̕P̸̧̤̭̖̬͖͚̞͖̖͖̣̝͚̦͙̓̔ͥͦ̅͐ͨͪ͐ͨ͋̂̄ͬ̏̔͒̔͑͟͟4̨͓̮͙̫͕̠̮̩̦͇͖͍̭̩̇ͤ͐̓ͫ̋̇͌̑́ͮ̑̔̒ͮ̾̚͢͢͝ḡ̢̲̭̜̭̩̠̣̭̰̞͎͕̩̰̾̍̐̇̈́͌̅̃̑̒̇̆́̀͘͡3ͮ̓͐ͮ҉̴̵̜͕̯͕̞̥͙̳͈̰̖́͡ ̢̉̓̊͂ͭ̋͌ͣ̎ͤͩ͟͞͏͕̳̥̥̘̯͉̠̻̠m͚̦̘̠̟̮̩ͪͣ̓̐̊͑̊ͬ̐̄ͬ́ͩ̓́͢͜0̧̡̘͙̺͇̝͖͎̮̦̪̩͎̠̇̎̏̀ͬ̓̏|̨̡̛̥̭͓̜͇̬̯̫̹͇͕̱̣̙ͦ̂̈́͆ͩ͗ͮ̾ͭ̾̿͋͋ͪ̏̀̄̚̕ͅ2̶̡̤͉͓̰̲͇ͣ͊̽ͫ̉̾̆ͭ͐̅͑̀̚͢͞3̵̿ͯ̋ͣ̓͋̿̈ͯ̏̎͌ͫͧ͑ͣͥͥ̇҉͏͔̭̼͇ ̄ͯ̎ͪ͊́҉̴̛̱̫̭̱̱͙̲͓̖̟̼̯̝̖h̵̷͎̹̰̝̼̭̲̪̖͈͎̦̮̽̽ͦ̄̋̊̓̂̃̀̓̿̂̕͜1̶̴̡͙̖̜͚̗̗̻̮̜̻̬͍̘ͯ͋ͮͯ̏ͨ͒g̴̢͒ͯ̽̉͆͑ͤ̅ͪͮͯ͠͏̱̺͉̜̦͍͓̫h̸̡ͥͭ̈́̀̈́ͪ̈̽ͦ́͝҉̲̱̠̼͖̻͚̬͙͔͈̺̣̗͍l̸̷͖̹̹͖̥̱̰̗̦̠͚ͯͬ͌̏͗̏̊̆ͥ̑̐͛̅̃ͤ̋̂͌͢1̷͉̖̞̠̗̮͓̬͇̩̦̥͎̙̖̺̟̼̾̉͋̑͒̐̕͟g̷̢̱͔̼̱͙͎̱̝̲̣ͯͥ̍͒̄̓̿̒͊ͩ͌͒̂̌̓̀͡h̨̛̘̖̟̪͔̗͙̹̹̲̱̳͍͎ͤ̂ͬ͛ͨ̎ͣͣ̄ͤͮ͋ͭ͂̊̈ͣ̍̎͘͢͜7̱̫̻̘̠̞̰͇̞̤̺̮̥̬̐̾̆͊̿̈̄̽ͫ͋͑̀ͥ̍ͯ̀3̘̣͎̮̠̬̘͗̑ͮͣ̿ͮ̿ͭ͛̿̐͐͂͌́͝ͅd̢̢͚̱̤͕͓̦̖̬̙̻̠̫͉͎̤̙͋̌́ͦ̅̊ͣ̇̐̌ͣͫ͗̍ͥ̚̚ͅͅ ̷̸̙͔͕̮̰̬͈͈͉͖̝̣̰͇͛̒ͬ̿̿̇͊ͬ̅͋́͒̿̑͆ͣ̓͐́̚͠i̵̛͕̺̼̬̩̗̲̦̠̔̒̈́̏̔́̚͢͝N̷̵̡͕͇͉̬̝̦̼̖͖̰̖̪̍̿̓͌̄̍ ̸̡̥͉̙̤̭͙̩̬̩͔͎̯̙̠̮̫̼̄̐̎͂ͥ̈ͪ̋ͫͅͅC̴̷̛͓̻̜̞̣̦̟̯̰̞̈̇ͫ̈́ͪͨ̍͐ͫ͝͠a͙̤͓̮̩͎̬̺̣͚̖̩̖̜̜͕̬ͯͬ̑͗̾̀͝Ň̳̘̳̜̩̮̲ͯͫ̿ͬ͒ͣ̆͑͋̋͒͛̀̚͝.ͩ͂͊̋͊ͣ̀̌͆̊ͯͮ̐̓͆́͆̅̍҉̡͉̲͔͉͠ ̷̹̟͚͓̟̘̝̦̗̖̟͕̘͈͑̀ͩ͊̕͘͠1̵̘̰͍͎̟̞̻͕̱̬̎̀͂̇̊͛̀̀+̷̴̄̾̾̎̌̈ͫ̉ͯͥ̊̓̋ͨ͊ͣ̑̇͏͉̩̯̫̤͇̳̘̯͕̹̪̲̟̰͡ ̒ͮͪ̒̓̚̕͞͏͖̻͍͝k̴̴̴͙̼̗͉̫̲͐̈́̿̂ͮ̽͞4̷̱̖̘͔̦̪̯̣̜̻̬͚̭̄̏̽̽̿̑̀̚N̟̞̺͇̳̖̫̲͉͙̻̬̟̬̭͕̆̅̿͛͂̅̋̾̑̌̽͒͗̽̆ͣ͜͞ṯ̷̭̤̰̦̲͔̭̤͉̊̈́͒ͮ̕ ̢͗̇͋̆̈́̅̒ͦͨ̏͋͛͒̿̐̓҉̫̣̬̯͖̟̞̹p̡͚̭͔͎̍ͥͨ̿ͨ̏̐́͟1̸̶͚͕͈̹͇̱̜̜̊̉ͩ̆̈́͌̏͌͟͞c̸̰͖̦͉̲͓͊ͮ̽̊ͣ̅ͩ̌̂͆̌́̾ͨ͐̎͌͡z̸̧̜̞͙̪̜̹̯̟̯̲̦͍͓͉̙̼ͬ̎̓͂͟͞ͅ!̷̧͕̬̦̙̯͙̦͈͙̥̩̘̦͍͚̜̬̓͛ͬ͋͗ ̓̅͛ͯͦ̔̌̄͆̑̐̍̑̾͋ͮ͞҉͎̹̖̬̹͖̬̞̼͘͢|̸̵̵̡̖̳͔̞̞͇͔͛̈́̑ͯͩ̑͌ͤ̇̐ͧͥ͡-̢̳̪͔̯͉͍͕͔̪̜̻̲̻̜͖͎̇ͪ̈̈͋ͨ͘|̷̧̛̥̱̩͍̏ͣͭ̏ͨͥ͆̆͛ͫ̑ͨ̉͡@͂͂͐͐ͫͤ̓҉̷̹͓̬͎̳͈̦̲v̶̛̬͕̟̣͖̖̤̫̥̦̏͒̿̅̽̇̍ͨͮ̑̎̚ͅͅ3̛̂́͂̀̚͝͏̮̟̟͇̳͍̤͔̹͇͍̱̜ ̴̴̡̹͕̟̝̥͓͕̗̾ͫͧ̋̒̓̅̚̚̕͘N̴̏ͩͤͣ͑̑ͥ̊ͨ̈̿ͮ̄̚҉̱̳̹̥̮̱͎̹̮͙̼̱̘͍̱͎̟o͕̦͚̯̣̰͍̬͍͉̻̪͙͚̳̅̿͑͆͛̃̓̊͋̒͋̀̕͡+̈̅͛́̽̈ͭ̉̄͌̑ͨ̅͆ͤ́̽̄͏̵̤̬̭̥̝̜̥͙̜̙̙̭.̛̱̘̖̱͉̬̯̑̀͒̿̔̀̉ͪ̉ͫ͗͛ͯ̇͋͊̋̀̕͠ ͣͪ͐̇ͬ҉̵̴̩̰̱̹͡D̸̸̨͍͍̤̳̟̻͆̓̈́͌͂̒̐ͬͪͬ̆̿ͩ̉̾ͭ͝0̨̧͕͍̤͇͉̺͉̪̪͇̗̲̙̪̫ͮ̅͌̽̋ͥ̒̑̏̈ͫ̐̊͒̈́̎̐̈́͜͟n̸̸̨̨̧̬̟̞̮̥͉̭̻̞̘͇͍̱̬̅ͪͤ͗̑̎T͗ͤͥ̂ͧ́ͫ҉̢͖͙͎͙̝͖̣̪̭̰̯͉͕͟͞ ̶̱̮̥̒̇ͣ̈̄ͣ̂̄̏ͬͬ̌̚̕͘͢͝…

**Comment by kenorb** [comment]
[ȇ̴̸̱̞̲͕̙̻̫̥̘͉̟ͮ̍͌ͫͭ̔̂̌̒̒̈́͝ͅe̸̵̥̤͕͈̯͙͉̻̪͇͖͆͑̿͗̇͑̆ͪ̽ͅe̛̹̹͇̮͕̼ͧͫ̓ͤ̔̍̂̀̔ͧ̆ͨ̀ͥͪ̉̊ͫ͡ȩ̶̪̥̖̺̖̲͉ͬ̄ͨ͑ͪͬ̊ͣ͊̔́͠e̵̖̟̜͍̱̥̲̻̦ͪ̽̀͌̆̾͑ͮ̇͛ͣ͒̄e̵̷̡̦̖̟͉̱̝̭̪͙̰̦͕̬͎͆͒͒ͭ̋̒̾͐̋̂̑ͧ͋͊̑̆̿͢ͅe̶̵̛̹̬͖̦̻͖̱̰͚̜̺̳͚͍̣̠͙͚ͮ̄ͮ̄͗ͅ](36)?
