### ISSUE TITLE
Good luck to you :)

### ISSUE THREAD

**Issue by wastes** [eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#435]
![screen shot 2018-12-10 at 7 28 28 pm](https://user-images.githubusercontent.com/36355276/49730036-19153a80-fcb2-11e8-8377-420fe5c825a9.png)

**Comment by kenorb** [comment]
[Ee-ee](https://gitlab.com/)?

**Comment by liuwensa** [comment]
？？？

**Comment by kenorb** [comment]
Abuse?

Try to print _Hello World_ the [Chicken language](https://esolangs.org/wiki/chicken), this is abuse.
Imagine all code in Chicken.

**Comment by LinuxMercedes** [comment]
Eeeee eee.
