### ISSUE TITLE
Oops. This project makes GitHub dirty.

### ISSUE THREAD

**Issue by shangchihh** [eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#456]
Oops. This project makes GitHub dirty. Which fucking guy create this repository? How can we punish these behaviors?

**Comment by LoganDark** [comment]
Oops. This comment makes this repository dirty. Which fucking guy create this comment? How can we punish these behaviors?

**Comment by bhalash** [comment]
@shangchihh eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by LoganDark** [comment]
@bhalash eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.

**Comment by gusg21** [comment]
Oopseeeeeeeeeeee,,,,,?;

**Comment by LoganDark** [comment]
eeeeeeeeeeee.

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/49736273-81c2cf80-fc3e-11e8-990f-a1587a5f72cf.png)
EEEEEEEEEE!

**Comment by gusg21** [comment]
EEEeEeeeeeEE

**Comment by LoganDark** [comment]
eeEEEeeeEEEeeeEEEeeeEEEEeeEEEEeeeEEEEEeeEEEEeeeEEEeeeE

**Comment by svenluijten** [comment]
e eee'e eeee eeeeee ee eeee, eee eeee'e eee eeeee e eeeeeee.

**Comment by neilbryson** [comment]
I just saw this in Explore and.. uh I meant to say

EEEEEEEEEEEEEEEEEEEEEEEEEEeeeeeeeeeeeEEeeE

**Comment by LoganDark** [comment]
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEe

**Comment by ACiep** [comment]
I don't agreeeeeeeeeeeeeeeeeeeeeeeeeee, because
- eeeeeeeee
- ee
- ee
- eeeeeee
- ee
- ee
- eeeeeeeee

**Comment by dfoster-cb911** [comment]
SCREEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

![screee](https://user-images.githubusercontent.com/38434111/49737010-a6787080-fc59-11e8-9182-9da9d7580213.jpg)

, quoth the raven.

**Comment by molvqingtai** [comment]
what eeeeeeeeee ？？？

**Comment by jordanwilson230** [comment]
@shangchihh Rather than calling some code dirty, please consider contributing to eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee with Pull Requests to help improve any areas you deem 'dirty'.  I cannot find any areas needing improvement, but am curious to see what code changes you have in mind.

**Comment by LinuxMercedes** [comment]
Eeee eee eee eeeeee eeee, eeeeee #207
