### ISSUE TITLE
Extra 'e' found on README.md

### ISSUE THREAD

**Issue by Otman404** [eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#495]
An extra 'e' must be removed on last line in README.md

**Comment by Unitech** [comment]
+1

**Comment by jordanwilson230** [comment]
Hmm, looks correct to me.  @Otman404 please look again, I believe you miscounted.  If not, we should collaborate on getting a PR opened.

We may need to escalate this issue and create a patch/hotfix if you're certain of the extra 'e'.

**Comment by Otman404** [comment]
I mean i can't be wrong after 2h of counting, just to be sure i'll check one more time as you asked @jordanwilson230

**Comment by ceneon** [comment]
eeEeEeeEeEeEE !! eeE? Ee

**Comment by LinuxMercedes** [comment]
Eee #169! Eee eee eee EEEE :e-mail: eeeeeee?
