### ISSUE TITLE
Mascot Proposal - EEE

### ISSUE THREAD

**Issue by channprj** [eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#509]
## eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeêeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeèeeeeeeeeeeeeeeeeeeeeeeeeë
![EEE](https://user-images.githubusercontent.com/1831308/49746901-91e1ba00-fce5-11e8-9a98-1e29354b948b.jpg)

This character name is EEE. It stands for our eeee project.

## Reference
- [10 Hours EEE](https://www.youtube.com/watch?v=IEPv31_E__4)

**Comment by hannahwhy** [comment]
Eeeeeeeee #128
