### ISSUE TITLE
Too much Assembleeeee

### ISSUE THREAD

**Issue by ghost** [eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#521]
This code is > 20% Assembleeeee! What about VBeeeeeeS? EeeeeeXEeeee? We need other languages or we'll never be able to support major operating systems! Who's ever heard of an OS that runs Assembleeeee? Who even knows what Assembleeeee is? Not me! We have to fix this enormous problem before all of our hard work is depreciated and inaccessible to the end user!

We need as many programs as possible to fix this! It's way too difficult to add in support for every OS out there, so we can instead convince our users that our code will work for them. It will take almost no thought, and barely any effort. What we need to do is add more of the underrepresented files so that all of the files are of an equal number. Then the Other category will be at 100%! Our users won't know what operating system we support, and combined with the EEEExceleeeent (TM) error handling we are going to implement, everything will run smoothly. Our Readme is unreadable, so users won't even realize that the program is doing the wrong thing!

**Comment by LinuxMercedes** [comment]
Eee eeeeeeee eee eeee eee :e-mail: !

**Comment by ghost** [comment]
Still too much Assembleeeee, why was this closeeeeeeed?
