### ISSUE TITLE
Breaking Github Explore

### ISSUE THREAD

**Issue by rahuldottech** [eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#549]
Snapshots:
https://web.archive.org/web/20181210200734/https://github.com/explore
http://archive.is/gghp1
http://www.webcitation.org/74ZIds0b3

**Comment by ghost** [comment]
eeee? [eee.](https://github.com/github/explore)

**Comment by bf4** [comment]
feature or bug?

**Comment by LinuxMercedes** [comment]
eeee E!  #282
