### ISSUE TITLE
Too much E

### ISSUE THREAD

**Issue by DealPete** [eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#552]
E is already the most common letter in the English alphabet, I don't see why we need more of it.

**Comment by sigwinch28** [comment]
We are preserving the status quo by producing more Es

**Comment by LinuxMercedes** [comment]
Eeee ee eeeee ee #169 !
