### ISSUE TITLE
What happened!!!!

### ISSUE THREAD

**Issue by CasterWx** [eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#554]
Did the repository disappear this morning

**Comment by sigwinch28** [comment]
E! https://linuxwit.ch/blog/2018/12/e98e/

**Comment by riptl** [comment]
Nice, I also contacted GitHub staff, saying this was a community research project testing the character stream speed on different languages.
I think this is a good way to excuse the repo.

**Comment by LinuxMercedes** [comment]
Eeeee eeee, eeee! :beer: :robot: :smoking:
